name: Build PowerShell Wrapper
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
        default: 'false'
permissions: {}

jobs:
  wrapper_build:
    if: github.event.inputs.type == 'ci'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Golang toolchain
        uses: actions/setup-go@v5
      - name: Build Powershell Wrapper (32bit)
        run: |
          make powershell32.exe
      - name: Upload 32bit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: powershell32-wrapper
          path: "powershell32.exe"
      - name: Build Powershell Wrapper (64bit)
        run: |
          make powershell64.exe
      - name: Upload 64bit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: powershell64-wrapper
          path: "powershell64.exe"
  release_build:
    if: github.event.inputs.type == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: upx-ucl
          version: pwsh_wrapper_release
      - name: Build Powershell Wrapper (Dist)
        run: |
          make dist
      - name: Upload 32bit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: powershell32-wrapper
          path: "powershell32.exe"
      - name: Upload 64bit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: powershell64-wrapper
          path: "powershell64.exe"
      - name: Upload Dist Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powershell-wrapper-dist
          path: powershell-wrapper.*