name: Powershell Wrapper Release
on:
  push:
    tags:
      - "v*.*.*"
permissions: {}

jobs:
  build_release:
    uses: ProjectSynchro/powershell-wrapper-for-wine/.github/workflows/build_release.yml@master
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build_release
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Download Artefacts
      uses: actions/download-artifact@v4
      with:
        path: .
        pattern: powershell*
        merge-multiple: true
    - name: Prep Staging Area
      run: |
        mkdir -p dist
        cp src/profile.ps1 ./dist
        cp *.exe ./dist
        cp *.zip ./dist
        cp *.tar.gz ./dist

        # Setup Checksums section
        echo >> CHANGELOG.md
        echo "## Checksums:" >> CHANGELOG.md
        echo >> CHANGELOG.md
        echo '```' >> CHANGELOG.md
        pushd ./dist
        files=("powershell32.exe" "powershell64.exe" "profile.ps1" "powershell-wrapper.zip" "powershell-wrapper.tar.gz")
        # Calculate and append SHA256 checksums to CHANGELOG.md
        for file in "${files[@]}"; do
            sha256sum "$file" >> ../CHANGELOG.md
            echo >> ../CHANGELOG.md  # Add a newline
        done
        popd
        echo '```' >> CHANGELOG.md
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/*"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        allowUpdates: true
        makeLatest: true