name: Powershell Wrapper Release
on:
  push:
    tags:
      - "v*.*.*"
permissions: {}

jobs:
  build_release:
    uses: ProjectSynchro/powershell-wrapper-for-wine/.github/workflows/build_release.yml@master
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build_release
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: build_release.yml
        workflow_conclusion: success
    - name: Prep Staging Area
      run: |
        mkdir -p dist
        cp src/profile.ps1 ./dist
        cp *.exe ./dist
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/*"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allowUpdates: true
        makeLatest: true